name: card_game
description: "Карточная игра для мобильных устройств"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Для работы с API
  http: ^1.2.2
  
  # State management
  provider: ^6.1.1
  
  # Локальное хранение
  shared_preferences: ^2.2.3
  
  # Анимации
  animations: ^2.0.8
  
  # Загрузка изображений
  cached_network_image: ^3.3.0
  
  # Для работы с JSON
  dartz: ^0.10.1
  
  # Для PostgreSQL (через Supabase)
  supabase_flutter: ^2.1.1
  
  # Для работы с .env файлами
  flutter_dotenv: ^5.1.0
  
  # Логирование
  logger: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.6 # для code generation

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/cards/
    - assets/icons/
    - assets/.env  # Добавляем .env в ассеты

# Android настройки
android:
  enable_jetifier: true
  namespace: com.example.card_game
  permissions:
    - android.permission.INTERNET

# iOS настройки
ios:
  supports_full_screen: true
  deployment_target: '11.0'
  info_plist:
    NSAppTransportSecurity:
      NSAllowsArbitraryLoads: true
    io.flutter.embedded_views_preview: true
    CFBundleURLTypes:
      - CFBundleURLSchemes:
          - io.supabase.flutter